language: php

php:
  - '7.1'
  - '7.2'

services:
  - mysql
  
before_script:
  - composer self-update
  - composer --version
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `stores`;'

install:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
